<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Global Model Permissions
    |--------------------------------------------------------------------------
    |
    | These values restrict the ability of users in a global manner.
    | They are evaluated before the policies are run to ensure that
    | the application is accepting CRUD. Useful to disable CRUD
    | once the System closes.
    */
    'email'                 => env('IPMS_EMAIL',''),
    'contact_info'          => env('IPMS_CONTACT_INFO', ''),
    'allow_google_login'    => env('ALLOW_GOOGLE_LOGIN', false),
    'allow_multiple_login'  => env('ALLOW_MULTIPLE_LOGIN', false),
    'ipms_manual_url'       => env('IPMS_MANUAL_URL',''),
    'permissions' => [
        'projects' => [
            'create'        => true,
            'update'        => true,
            'delete'        => true,
            'restore'       => true,
            'forceDelete'   => true,
        ],
    ],
    'editor' => [
        'years' => [
            '2016',
            '2017',
            '2018',
            '2019',
            '2020',
            '2021',
            '2022',
            '2023',
            '2024',
        ],
    ],
    // Use to seed permissions
    'allPermissions' => [
        'projects.create',
        'projects.view_any',
        'projects.update_any',
        'projects.delete_any',
        'projects.view_office',
        'projects.update_office',
        'projects.delete_office',
        'projects.view_own',
        'projects.update_own',
        'projects.delete_own',
        'projects.view_assigned',
        'subprojects.create',
        'subprojects.view_index',
        'subprojects.view_office',
        'subprojects.view_any',
        'subprojects.update_own',
        'subprojects.update_office',
        'subprojects.update_any',
        'subprojects.delete_own',
        'subprojects.delete_office',
        'subprojects.delete_any',
        'reviews.create',
        'reviews.view_index',
        'reviews.view_office',
        'reviews.view_any',
        'reviews.update_own',
        'reviews.update_office',
        'reviews.update_any',
        'reviews.delete_own',
        'reviews.delete_office',
        'reviews.delete_any',
        'libraries.create',
        'libraries.view',
        'libraries.update',
        'libraries.delete',
        'libraries.view_index',
        'users.create',
        'users.view',
        'users.update',
        'users.delete',
        'users.view_index',
        'roles.view_index',
        'roles.create',
        'roles.view',
        'roles.update',
        'roles.delete',
        'permissions.view_index',
        'permissions.create',
        'permissions.view',
        'permissions.update',
        'permissions.delete',
        'projects.manage',
        'teams.view_index',
        'teams.create',
        'teams.view',
        'teams.update',
        'teams.delete',
        'audit_logs.view_index',
        'audit_logs.create',
        'audit_logs.view',
        'audit_logs.update',
        'audit_logs.delete',
    ],
];
